import { useEffect, useState, useCallback } from 'react';
import api from '../api/client';

/**
 * AI Insights page — heuristic pattern explanations and recommendations.
 * Pulls from live fatigue/baseline data; does NOT make medical claims.
 */
export default function AIInsights() {
  const [soldiers, setSoldiers] = useState([]);
  const [insights, setInsights] = useState([]);
  const [loading, setLoading] = useState(true);

  const generateInsights = useCallback((soldiers) => {
    const out = [];
    for (const s of soldiers) {
      const fa = s.latest_fatigue;
      if (!fa) continue;
      const score = fa.fatigue_score ?? 0;
      const cat = fa.risk_category ?? 'NORMAL';
      const c = fa.contributors ?? {};

      if (cat === 'CRITICAL') {
        out.push({
          soldier: s,
          severity: 'critical',
          title: `Critical fatigue risk — ${s.name}`,
          body: `Score ${score.toFixed(0)}/100. Dominant contributors: ${topContributors(c)}. Recommend immediate rest rotation and assessment.`,
          action: 'Immediate rest rotation recommended.',
        });
      } else if (cat === 'HIGH') {
        out.push({
          soldier: s,
          severity: 'high',
          title: `High fatigue — ${s.name}`,
          body: `Score ${score.toFixed(0)}/100. Top factors: ${topContributors(c)}. Monitor closely; consider workload redistribution.`,
          action: 'Monitor and consider workload redistribution.',
        });
      } else if (cat === 'ELEVATED') {
        out.push({
          soldier: s,
          severity: 'elevated',
          title: `Elevated fatigue — ${s.name}`,
          body: `Score ${score.toFixed(0)}/100. Early fatigue indicators detected: ${topContributors(c)}.`,
          action: 'Schedule hydration and rest break.',
        });
      }

      if (!fa.baseline_valid) {
        out.push({
          soldier: s,
          severity: 'info',
          title: `Baseline calibrating — ${s.name}`,
          body: `Personal physiological baseline not yet validated (needs ≥30 readings). Current scores use population-level defaults — may be less accurate.`,
          action: null,
        });
      }
    }

    if (out.length === 0) {
      out.push({
        soldier: null,
        severity: 'info',
        title: 'All personnel within normal parameters',
        body: 'No elevated fatigue indicators detected across monitored soldiers. System is running nominal.',
        action: null,
      });
    }

    return out;
  }, []);

  const load = useCallback(async () => {
    try {
      const sol = await api.soldiers.list().catch(() => []);
      const detailed = await Promise.all(
        sol.map(s =>
          api.soldiers.fatigue(s.id)
            .then(fa => ({ ...s, latest_fatigue: fa }))
            .catch(() => ({ ...s, latest_fatigue: null }))
        )
      );
      setSoldiers(detailed);
      setInsights(generateInsights(detailed));
    } finally {
      setLoading(false);
    }
  }, [generateInsights]);

  useEffect(() => { load(); const t = setInterval(load, 15000); return () => clearInterval(t); }, [load]);

  const sev = {
    critical: { bg:'var(--critical-dim)', border:'var(--critical)', color:'var(--critical)', icon:'🔴' },
    high:     { bg:'var(--high-dim)',     border:'var(--high)',     color:'var(--high)',     icon:'🟠' },
    elevated: { bg:'var(--elevated-dim)', border:'var(--elevated)', color:'var(--elevated)', icon:'🟡' },
    info:     { bg:'var(--bg-surface)',   border:'var(--border)',   color:'var(--accent)',   icon:'ℹ' },
  };

  return (
    <>
      <div className="page-header">
        <h1 className="page-title">AI Insights</h1>
        <span style={{fontSize:'0.78rem', color:'var(--text-muted)'}}>Heuristic pattern analysis — refreshes every 15s</span>
      </div>

      <div className="card" style={{
        background:'var(--elevated-dim)', border:'1px solid var(--elevated)',
        fontSize:'0.8rem', color:'var(--elevated)', lineHeight:1.5
      }}>
        ⚠ DISCLAIMER: Insights are generated by a rule-based heuristic prototype. 
        They are NOT AI/ML predictions and NOT clinically validated recommendations. 
        This system is for SIH demonstration purposes only. 
        Do not use for actual medical or operational decisions.
      </div>

      {loading ? (
        <div className="state-center"><div className="spinner-ring" /></div>
      ) : (
        <div style={{display:'flex', flexDirection:'column', gap:'0.75rem'}}>
          {insights.map((ins, i) => {
            const s = sev[ins.severity] ?? sev.info;
            return (
              <div key={i} style={{
                padding:'1rem 1.25rem',
                borderRadius:'var(--r-lg)',
                background: s.bg,
                border: `1px solid ${s.border}`,
              }}>
                <div style={{display:'flex', alignItems:'center', gap:'0.6rem', marginBottom:'0.5rem'}}>
                  <span style={{fontSize:'1.1rem'}}>{s.icon}</span>
                  <span style={{fontWeight:600, color: s.color}}>{ins.title}</span>
                  {ins.soldier && (
                    <span style={{
                      fontSize:'0.7rem', fontFamily:'var(--font-mono)',
                      color:'var(--text-muted)', marginLeft:'0.25rem'
                    }}>
                      {ins.soldier.soldier_uid}
                    </span>
                  )}
                </div>
                <p style={{fontSize:'0.85rem', color:'var(--text-secondary)', lineHeight:1.6}}>
                  {ins.body}
                </p>
                {ins.action && (
                  <div style={{
                    marginTop:'0.6rem', padding:'0.35rem 0.75rem',
                    background:'var(--bg-overlay)', borderRadius:'var(--r-sm)',
                    fontSize:'0.78rem', fontWeight:500, color:'var(--text-primary)',
                    display:'inline-block'
                  }}>
                    💡 {ins.action}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Overall soldier table */}
      {soldiers.length > 0 && (
        <div className="card" style={{padding:0}}>
          <div style={{padding:'1rem 1.25rem', borderBottom:'1px solid var(--border)', fontWeight:600}}>
            All Soldiers — Current Status
          </div>
          <div className="table-wrap" style={{border:'none', borderRadius:0}}>
            <table>
              <thead>
                <tr>
                  <th>UID</th>
                  <th>Name</th>
                  <th>Rank</th>
                  <th>Fatigue</th>
                  <th>Risk</th>
                  <th>HR contrib.</th>
                  <th>HRV contrib.</th>
                  <th>Baseline</th>
                </tr>
              </thead>
              <tbody>
                {soldiers.map(s => {
                  const fa = s.latest_fatigue;
                  const cat = fa?.risk_category ?? 'NORMAL';
                  return (
                    <tr key={s.id}>
                      <td className="mono text-accent" style={{fontSize:'0.8rem'}}>{s.soldier_uid}</td>
                      <td>{s.name}</td>
                      <td style={{color:'var(--text-muted)'}}>{s.rank}</td>
                      <td className="mono">{fa?.fatigue_score?.toFixed(1) ?? '—'}</td>
                      <td>
                        <span className={`badge badge-${cat.toLowerCase()}`}>{cat}</span>
                      </td>
                      <td className="mono" style={{fontSize:'0.8rem'}}>
                        {fa?.contributors?.hr_deviation != null
                          ? `${(fa.contributors.hr_deviation * 100).toFixed(0)}%` : '—'}
                      </td>
                      <td className="mono" style={{fontSize:'0.8rem'}}>
                        {fa?.contributors?.hrv_deterioration != null
                          ? `${(fa.contributors.hrv_deterioration * 100).toFixed(0)}%` : '—'}
                      </td>
                      <td style={{fontSize:'0.8rem', color: fa?.baseline_valid ? 'var(--ok)' : 'var(--text-muted)'}}>
                        {fa?.baseline_valid ? '✓ Valid' : '⟳ Calibrating'}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </>
  );
}

function topContributors(c) {
  return Object.entries(c)
    .sort(([,a], [,b]) => b - a)
    .slice(0, 2)
    .map(([k, v]) => `${k.replace(/_/g, ' ')} (${(v * 100).toFixed(0)}%)`)
    .join(', ');
}
